spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
server.port=${PORT:8080}

# 本機啟動預設 dev 模式
spring.profiles.active=dev