spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
server.port=${PORT:8080}

# 本機啟動預設 dev 模式
spring.profiles.active=dev
# 確保 SQL 初始化檔案以 UTF-8 讀取，避免中文亂碼
spring.sql.init.encoding=UTF-8
